Repository UBC-MDS/edapython, pull requests merged in 2020-03, with the labels that each got.

#42 implemented describe_num_var and its test function
  eda_analysis/eda_analysis.py
  tests/test_eda_analysis.py
Labels: enhancement

#44 added documentation for the test_describe_num_var function
  tests/test_eda_analysis.py
Labels: documentation

#39 Correlation eda
  eda_analysis/eda_analysis.py
  tests/test_eda_analysis.py
Labels: enhancement

#45 generated documentation .html from poetry
  README.md
  docs/conf.py
  docs/source/eda_analysis.rst
  docs/source/modules.rst
  docs/source/tests.rst
  poetry.lock
  pyproject.toml
Labels: documentation

#43 Implemented describe_cat_var function and its test. Also contains helper function to create data
  eda_analysis/eda_analysis.py
  tests/test_eda_analysis.py
Labels: enhancement

#49 Implemented generate report and its test function
  eda_analysis/eda_analysis.py
  tests/test_eda_analysis.py
Labels: enhancement

#50 updated the documentation badge
  README.md
Labels: documentation

#51 hard workaround for badge status
  README.md
Labels: documentation

#69 docs: few more changes supporting CD and CI
  docs/conf.py
  poetry.lock
  pyproject.toml
  src/eda_analysis/eda_analysis.py
  tests/test_eda_analysis.py
Labels: enhancement

#67 Included example in README.md and linked to contributors in CONTRIBUTORS.md
  CONTRIBUTORS.md
  README.md
  img/report.png
  poetry.lock
  pyproject.toml
  src/eda_analysis/eda_analysis.py
Labels: enhancement

#70 fix: restructured folder to enable CD
  .gitignore
  README.md
  eda_analysis/__init__.py
  eda_analysis/eda_analysis.py
  poetry.lock
  src/eda_analysis/__init__.py
  tests/test_eda_analysis.py
Labels: documentation

#72 fix: added bot to temporarily turn off branch protection for CD
  .github/workflows/release.yml
Labels: bug

#74 fix: resolved duplicate tags in `release.yml`
  .github/workflows/release.yml
  README.md
  pyproject.toml
Labels: bug

#75 fix: re-wrote release.yml
  .github/workflows/release.yml
  eda_analysis/__init__.py
Labels: bug

#86 added one-line descriptions for test
  tests/test_eda_analysis.py
Labels: documentation

#95 reduced font size for the correlation plot
  eda_analysis/eda_analysis.py
Labels: documentation
